-- Heights seed — run this in the Supabase SQL editor.
--
-- FIRST: fixes a community-id mismatch. The earlier setup script seeded
-- settings under 'heights', but the registry id (and therefore the id the
-- tool reads) is 'heights-uptown'. Those rows were orphaned. This migrates
-- them and removes the stale ones.
--
-- THEN: seeds lot ownership for all 227 lots (179 non-OCH marked excluded)
-- and the 26 built homes.
--
-- Safe to re-run. Does not touch grandoaks-1b.

-- 1. migrate the orphaned 'heights' settings to 'heights-uptown'
insert into community_settings (community, key, value, updated_by)
  select 'heights-uptown', key, value, 'migration'
  from community_settings where community = 'heights'
on conflict (community, key) do update
  set value = excluded.value, updated_at = now();

delete from community_settings where community = 'heights';
delete from lot_state          where community = 'heights';
delete from change_log         where community = 'heights';

-- 2. lot ownership + built homes
insert into lot_state (community,block,lot,plan_id,excluded,updated_by) values
  ('heights-uptown','G',11,null,true,'setup'),
  ('heights-uptown','G',12,null,true,'setup'),
  ('heights-uptown','G',13,null,true,'setup'),
  ('heights-uptown','G',14,null,true,'setup'),
  ('heights-uptown','G',15,null,true,'setup'),
  ('heights-uptown','G',16,null,true,'setup'),
  ('heights-uptown','G',17,null,true,'setup'),
  ('heights-uptown','G',18,null,true,'setup'),
  ('heights-uptown','G',19,null,true,'setup'),
  ('heights-uptown','G',20,null,true,'setup'),
  ('heights-uptown','G',21,null,true,'setup'),
  ('heights-uptown','G',22,null,true,'setup'),
  ('heights-uptown','G',23,null,true,'setup'),
  ('heights-uptown','G',24,null,true,'setup'),
  ('heights-uptown','K',1,null,true,'setup'),
  ('heights-uptown','K',2,null,true,'setup'),
  ('heights-uptown','K',3,null,true,'setup'),
  ('heights-uptown','K',4,null,true,'setup'),
  ('heights-uptown','K',5,null,true,'setup'),
  ('heights-uptown','K',6,null,true,'setup'),
  ('heights-uptown','K',7,null,true,'setup'),
  ('heights-uptown','K',8,null,true,'setup'),
  ('heights-uptown','K',9,null,true,'setup'),
  ('heights-uptown','K',10,null,true,'setup'),
  ('heights-uptown','K',11,null,true,'setup'),
  ('heights-uptown','K',12,null,true,'setup'),
  ('heights-uptown','K',13,null,true,'setup'),
  ('heights-uptown','K',14,null,true,'setup'),
  ('heights-uptown','K',15,null,true,'setup'),
  ('heights-uptown','K',16,null,true,'setup'),
  ('heights-uptown','K',17,null,true,'setup'),
  ('heights-uptown','K',18,null,true,'setup'),
  ('heights-uptown','K',19,null,true,'setup'),
  ('heights-uptown','K',20,null,false,'setup'),
  ('heights-uptown','K',21,null,false,'setup'),
  ('heights-uptown','K',22,null,true,'setup'),
  ('heights-uptown','K',23,null,true,'setup'),
  ('heights-uptown','K',24,null,true,'setup'),
  ('heights-uptown','K',25,null,true,'setup'),
  ('heights-uptown','K',26,null,true,'setup'),
  ('heights-uptown','K',27,null,true,'setup'),
  ('heights-uptown','K',28,null,true,'setup'),
  ('heights-uptown','K',29,null,true,'setup'),
  ('heights-uptown','K',30,null,true,'setup'),
  ('heights-uptown','K',31,null,true,'setup'),
  ('heights-uptown','L',1,null,true,'setup'),
  ('heights-uptown','L',2,null,false,'setup'),
  ('heights-uptown','L',3,null,true,'setup'),
  ('heights-uptown','L',4,null,true,'setup'),
  ('heights-uptown','L',5,null,true,'setup'),
  ('heights-uptown','L',6,null,true,'setup'),
  ('heights-uptown','L',7,null,true,'setup'),
  ('heights-uptown','L',8,null,true,'setup'),
  ('heights-uptown','L',9,null,false,'setup'),
  ('heights-uptown','L',10,null,false,'setup'),
  ('heights-uptown','L',11,null,false,'setup'),
  ('heights-uptown','L',12,null,false,'setup'),
  ('heights-uptown','L',13,null,true,'setup'),
  ('heights-uptown','L',14,null,true,'setup'),
  ('heights-uptown','L',15,null,false,'setup'),
  ('heights-uptown','L',16,null,false,'setup'),
  ('heights-uptown','L',17,'pearl_a',false,'setup'),
  ('heights-uptown','L',18,null,true,'setup'),
  ('heights-uptown','L',19,null,true,'setup'),
  ('heights-uptown','L',20,null,true,'setup'),
  ('heights-uptown','M',1,null,true,'setup'),
  ('heights-uptown','M',2,null,true,'setup'),
  ('heights-uptown','M',3,null,true,'setup'),
  ('heights-uptown','M',4,null,true,'setup'),
  ('heights-uptown','M',5,null,true,'setup'),
  ('heights-uptown','M',7,null,true,'setup'),
  ('heights-uptown','M',8,null,true,'setup'),
  ('heights-uptown','M',9,null,true,'setup'),
  ('heights-uptown','M',10,null,true,'setup'),
  ('heights-uptown','M',12,null,true,'setup'),
  ('heights-uptown','M',13,null,true,'setup'),
  ('heights-uptown','M',14,null,true,'setup'),
  ('heights-uptown','M',15,null,true,'setup'),
  ('heights-uptown','M',16,null,true,'setup'),
  ('heights-uptown','M',17,null,true,'setup'),
  ('heights-uptown','M',18,null,true,'setup'),
  ('heights-uptown','M',19,null,true,'setup'),
  ('heights-uptown','M',20,null,true,'setup'),
  ('heights-uptown','M',21,null,true,'setup'),
  ('heights-uptown','M',22,null,false,'setup'),
  ('heights-uptown','M',23,null,false,'setup'),
  ('heights-uptown','M',24,null,true,'setup'),
  ('heights-uptown','M',25,null,true,'setup'),
  ('heights-uptown','M',26,null,true,'setup'),
  ('heights-uptown','M',27,null,true,'setup'),
  ('heights-uptown','M',28,null,true,'setup'),
  ('heights-uptown','M',29,null,true,'setup'),
  ('heights-uptown','M',30,null,true,'setup'),
  ('heights-uptown','M',31,null,true,'setup'),
  ('heights-uptown','M',32,null,true,'setup'),
  ('heights-uptown','M',33,null,true,'setup'),
  ('heights-uptown','M',34,null,true,'setup'),
  ('heights-uptown','M',35,null,true,'setup'),
  ('heights-uptown','N',1,'addison_b',false,'setup'),
  ('heights-uptown','N',2,null,false,'setup'),
  ('heights-uptown','N',3,'carmichael_b',false,'setup'),
  ('heights-uptown','N',4,'parker_b',false,'setup'),
  ('heights-uptown','N',5,'carmichael_a',false,'setup'),
  ('heights-uptown','N',6,'addison_b',false,'setup'),
  ('heights-uptown','N',7,'carmichael_c',false,'setup'),
  ('heights-uptown','N',8,null,false,'setup'),
  ('heights-uptown','N',9,null,true,'setup'),
  ('heights-uptown','N',10,null,true,'setup'),
  ('heights-uptown','N',11,null,true,'setup'),
  ('heights-uptown','N',12,null,false,'setup'),
  ('heights-uptown','N',13,'parker_a',false,'setup'),
  ('heights-uptown','N',14,null,false,'setup'),
  ('heights-uptown','N',15,'logan_c',false,'setup'),
  ('heights-uptown','N',16,null,true,'setup'),
  ('heights-uptown','N',17,null,true,'setup'),
  ('heights-uptown','N',18,null,true,'setup'),
  ('heights-uptown','N',19,null,true,'setup'),
  ('heights-uptown','N',20,null,false,'setup'),
  ('heights-uptown','N',21,null,false,'setup'),
  ('heights-uptown','N',22,'crowder_a',false,'setup'),
  ('heights-uptown','N',23,'crowder_c',false,'setup'),
  ('heights-uptown','N',24,null,true,'setup'),
  ('heights-uptown','N',25,null,true,'setup'),
  ('heights-uptown','N',26,null,true,'setup'),
  ('heights-uptown','N',27,'addison_c',false,'setup'),
  ('heights-uptown','N',28,'addison_a',false,'setup'),
  ('heights-uptown','P',1,'knox_b',false,'setup'),
  ('heights-uptown','P',2,'crowder_a',false,'setup'),
  ('heights-uptown','P',3,null,true,'setup'),
  ('heights-uptown','P',4,null,true,'setup'),
  ('heights-uptown','P',6,'crowder_b',false,'setup'),
  ('heights-uptown','P',7,'logan_a',false,'setup'),
  ('heights-uptown','P',8,null,false,'setup'),
  ('heights-uptown','P',9,null,true,'setup'),
  ('heights-uptown','P',10,null,true,'setup'),
  ('heights-uptown','P',11,null,true,'setup'),
  ('heights-uptown','P',12,'carmichael_b',false,'setup'),
  ('heights-uptown','P',13,'thompson_a',false,'setup'),
  ('heights-uptown','P',14,null,true,'setup'),
  ('heights-uptown','P',15,null,true,'setup'),
  ('heights-uptown','P',16,null,false,'setup'),
  ('heights-uptown','P',17,'parker_a',false,'setup'),
  ('heights-uptown','P',18,'carmichael_c',false,'setup'),
  ('heights-uptown','P',19,null,true,'setup'),
  ('heights-uptown','P',20,null,true,'setup'),
  ('heights-uptown','P',21,null,true,'setup'),
  ('heights-uptown','P',22,'thompson_b',false,'setup'),
  ('heights-uptown','P',23,null,true,'setup'),
  ('heights-uptown','P',24,'carmichael_a',false,'setup'),
  ('heights-uptown','Q',1,null,true,'setup'),
  ('heights-uptown','Q',2,null,true,'setup'),
  ('heights-uptown','Q',3,null,true,'setup'),
  ('heights-uptown','Q',4,null,true,'setup'),
  ('heights-uptown','Q',5,null,true,'setup'),
  ('heights-uptown','Q',6,null,true,'setup'),
  ('heights-uptown','Q',7,null,true,'setup'),
  ('heights-uptown','Q',8,null,true,'setup'),
  ('heights-uptown','Q',9,null,true,'setup'),
  ('heights-uptown','Q',10,null,true,'setup'),
  ('heights-uptown','Q',11,null,true,'setup'),
  ('heights-uptown','Q',12,null,true,'setup'),
  ('heights-uptown','Q',13,null,true,'setup'),
  ('heights-uptown','Q',14,null,true,'setup'),
  ('heights-uptown','Q',15,null,true,'setup'),
  ('heights-uptown','Q',16,null,true,'setup'),
  ('heights-uptown','R',1,null,true,'setup'),
  ('heights-uptown','R',2,null,true,'setup'),
  ('heights-uptown','R',3,null,true,'setup'),
  ('heights-uptown','R',4,null,true,'setup'),
  ('heights-uptown','R',5,null,true,'setup'),
  ('heights-uptown','R',6,null,true,'setup'),
  ('heights-uptown','R',7,null,true,'setup'),
  ('heights-uptown','R',8,null,true,'setup'),
  ('heights-uptown','R',9,null,true,'setup'),
  ('heights-uptown','R',10,null,true,'setup'),
  ('heights-uptown','R',11,null,true,'setup'),
  ('heights-uptown','R',12,null,true,'setup'),
  ('heights-uptown','R',13,null,true,'setup'),
  ('heights-uptown','R',14,null,true,'setup'),
  ('heights-uptown','R',15,null,true,'setup'),
  ('heights-uptown','R',16,null,true,'setup'),
  ('heights-uptown','R',17,null,true,'setup'),
  ('heights-uptown','R',18,null,true,'setup'),
  ('heights-uptown','R',19,null,true,'setup'),
  ('heights-uptown','R',20,null,true,'setup'),
  ('heights-uptown','R',21,null,true,'setup'),
  ('heights-uptown','R',22,null,true,'setup'),
  ('heights-uptown','R',23,null,true,'setup'),
  ('heights-uptown','R',24,null,true,'setup'),
  ('heights-uptown','S',7,null,true,'setup'),
  ('heights-uptown','S',8,null,false,'setup'),
  ('heights-uptown','S',9,'carmichael_a',false,'setup'),
  ('heights-uptown','S',10,null,true,'setup'),
  ('heights-uptown','S',11,null,true,'setup'),
  ('heights-uptown','S',12,null,true,'setup'),
  ('heights-uptown','T',1,null,true,'setup'),
  ('heights-uptown','T',2,null,true,'setup'),
  ('heights-uptown','T',3,null,true,'setup'),
  ('heights-uptown','T',4,null,true,'setup'),
  ('heights-uptown','T',5,null,true,'setup'),
  ('heights-uptown','T',6,null,true,'setup'),
  ('heights-uptown','T',7,null,true,'setup'),
  ('heights-uptown','U',1,null,true,'setup'),
  ('heights-uptown','U',2,null,true,'setup'),
  ('heights-uptown','U',3,null,true,'setup'),
  ('heights-uptown','U',4,null,true,'setup'),
  ('heights-uptown','U',5,null,true,'setup'),
  ('heights-uptown','U',6,null,true,'setup'),
  ('heights-uptown','U',7,null,true,'setup'),
  ('heights-uptown','U',8,'holland_c',false,'setup'),
  ('heights-uptown','U',9,'addison_b',false,'setup'),
  ('heights-uptown','U',10,null,true,'setup'),
  ('heights-uptown','U',11,null,true,'setup'),
  ('heights-uptown','U',12,null,true,'setup'),
  ('heights-uptown','U',13,null,true,'setup'),
  ('heights-uptown','U',14,null,true,'setup'),
  ('heights-uptown','U',15,null,true,'setup'),
  ('heights-uptown','U',16,null,true,'setup'),
  ('heights-uptown','U',17,null,true,'setup'),
  ('heights-uptown','V',17,null,true,'setup'),
  ('heights-uptown','V',18,null,true,'setup'),
  ('heights-uptown','V',19,null,true,'setup'),
  ('heights-uptown','V',20,null,true,'setup'),
  ('heights-uptown','X',1,null,false,'setup'),
  ('heights-uptown','X',2,null,true,'setup'),
  ('heights-uptown','Y',2,null,false,'setup'),
  ('heights-uptown','Y',3,null,true,'setup')
on conflict (community,block,lot) do update
  set plan_id=excluded.plan_id, excluded=excluded.excluded, updated_at=now();

insert into community_settings (community,key,value) values
  ('heights-uptown','mono_rule','r3')
on conflict (community,key) do update set value=excluded.value, updated_at=now();

-- 3. verify
select community, count(*) as settings from community_settings group by community order by community;
select community, excluded, count(*) as lots from lot_state group by community, excluded order by community, excluded;
